-------estudos oracle----------

--criação do meu usuario

CREATE USER VINI
IDENTIFIED BY vini
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on users
QUOTA 0 on system;


GRANT CONNECT , RESOURCE TO VINI;


GRANT CREATE SESSION ,CREATE VIEW , CREATE TABLE , ALTER SESSION , CREATE SEQUENCE , CREATE PROCEDURE , CREATE TRIGGER TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK , UNLIMITED TABLESPACE TO HR;


------ dei todos os acessos agora a ele-- atraves do meu usuario adm sys 



