// DEFININDO CONSTANTES
//QUANDO COLOCAR UMA CONSTANTE NO DECLARE ELA NAO SER ALTERADA DURANTE O BEGIN 

SET SEVEROUTPUT ON;

DECLARE

vPi CONSTANT NUMBER (38,15) := 3.14586849684;

BEGIN
	DBMSOUTPUT.PUT_LINE('PI = '||vPi)
END;
